import gps, items, npcs

yeetRoom = gps.Location("The Grand Hall Of Yeet","an ornate hall with the word 'yeet' spray painted on the walls")
yeet1 = items.Item("Dude Item 1",99,"A item of a dude","Trinket")
yeet2 = items.Item("Dude Item 2",97,"A second item of a dude","Trinket")
yeet3 = items.Item("Dude Item 3",98,"A third item of a dude","Trinket")
yeet4 = items.Weapon("Dude Weapon",97,"The sword of the true dude","Sword","negatives",1,21)
dude = npcs.NPC("Dude","A normal dude")
dude.additem(yeet1)
dude.additem(yeet3)
dude.additem(yeet4)
dude.addline("La la lala la laa, just a boring dude")
scary = npcs.Enemy("Darth Batula","An Evil Vampire Bat",10,5)
scary.addline("I am darth batula, ha ha ha haaaa")
yeetRoom.link_npc(dude,"dude")
yeetRoom.link_item(yeet2,"small trinket")
yeetRoom.link_npc(scary,"bat")
place2 = gps.Location("The Cave I Guess","a dark and gloomy cave")
yeetRoom.link_location(place2,"cave","hall")
suicide = npcs.Enemy("Thanos","A strange purple man",100,69,False,True)
yeetRoom.link_npc(suicide,"purple man")
player  = Player()
player.move(yeetRoom)
fists = items.Weapon("Bare Knuckles",0,"Your fists","Unarmed","conversion",2,4)
god = items.Weapon("Op Weapon Of Doom",2,"A super op dev weapon","Mace","facts",2,10000000000)
yeetRoom.link_item(god,"large mace")
bod = npcs.Merchant("Bod","A friendly merchant")
player.equipedWeapon = fists
yeetRoom.link_npc(bod,"merchant")
healyboi = items.Potion("Basic Health Potion",10,"A potion used to heal oneself",50)
yeetRoom.link_item(healyboi,"health potion")
stupid = items.Item("Buy Me",3,"A test item to buy from a merchant","Laptop")
bod.additem(stupid)